// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BuyTicketBackBtn: typeof import('./src/components/BuyTicketBackBtn.vue')['default']
    Human: typeof import('./src/components/human/human.vue')['default']
    IconTriangle: typeof import('./src/components/IconTriangle.vue')['default']
    IconWarning: typeof import('./src/components/IconWarning.vue')['default']
    MapInfoBox: typeof import('./src/components/MapInfoBox.vue')['default']
    MenuContainer: typeof import('./src/components/layouts/MenuContainer.vue')['default']
    NavBox: typeof import('./src/components/NavBox.vue')['default']
    PageWrapperCol: typeof import('./src/components/PageWrapperCol.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeechCardCol: typeof import('./src/components/pageSpeech/SpeechCardCol.vue')['default']
    SpeechCardRow: typeof import('./src/components/pageSpeech/SpeechCardRow.vue')['default']
    SpeechTip: typeof import('./src/components/SpeechTip.vue')['default']
    SubwayFoot: typeof import('./src/components/SubwayFoot.vue')['default']
    SubwayHead: typeof import('./src/components/pagehead/SubwayHead.vue')['default']
    TtsGif: typeof import('./src/components/tts/TtsGif.vue')['default']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanList: typeof import('vant/es')['List']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
